=== repometric/linterhub/schema/meta.json
{
    "id": "https://repometric.github.io/linterhub/schema/meta.json",
    "$schema": "http://json-schema.org/draft-04/schema",
    "title": "This schema describes the engine definition",
    "description": "The meta information of engine",
    "type": "object",
    "properties": {
        "id": {
            "type": "string",
            "description": "The engine id, used only when the engine name is not unique",
            "default": ""
        },
        "name": {
            "type": "string",
            "description": "The engine official name, may not be unique"
        },
        "alias": {
            "type": "array",
            "description": "List of engine aliases.",
            "items": {
                "type": "string"
            }
        },
        "description": {
            "type": "string",
            "description": "The engine official description"
        },
        "url": {
            "type": "string",
            "description": "The engine url (homepage, documentation or repository)",
            "format": "uri"
        },
        "languages": {
            "type": "array",
            "description": "The list of supported languages",
            "items": {
                "$ref": "#/definitions/language"
            }
        },
        "extensions": {
            "type": "array",
            "description": "Common file extensions parsed by engine, if empty then corresponding language extensions are used",
            "items": {
                "oneOf": [
                    {
                        "$ref": "#/definitions/extension"
                    },
                    {
                        "$ref": "#/definitions/language"
                    }
                ]
            }
        },
        "configs": {
            "type": "array",
            "description": "List of file names which could be treated as engine config",
            "items": {
                "type": "string"
            }
        },
        "license": {
            "type": "string",
            "description": "The engine license",
            "$ref": "#/definitions/license"
        },
        "agreement": {
            "type": "string",
            "description": "The engine custom agreement"
        }
    },
    "required": [
        "name",
        "description",
        "license"
    ],
    "additionalProperties": true,
    "definitions": {
        "license": {
            "type": "string",
            "description": "The engine license",
            "oneOf": [
                {
                    "type": "string",
                    "enum": [
                        "custom"
                    ]
                },
                {
                    "$ref": "https://repometric.github.io/linterhub/schema/license.json"
                }
            ]
        },
        "language": {
            "description": "The programming language",
            "type": "string",
            "oneOf": [
                {
                    "type": "string",
                    "enum": [
                        "any"
                    ]
                },
                {
                    "$ref": "https://repometric.github.io/linterhub/schema/language.json"
                }
            ]
        },
        "extension": {
            "description": "The filename extension",
            "type": "string",
            "pattern": "^\\..*"
        }
    }
}

=== repometric/linterhub/engine/prettier/meta.json
{
    "$schema": "https://repometric.github.io/linterhub/schema/meta.json",
    "name": "prettier",
    "description": "Prettier is an opinionated code formatter. It enforces a consistent style by parsing your code and re-printing it with its own rules that take the maximum line length into account, wrapping code when necessary.",
    "url": "https://github.com/prettier/prettier",
    "languages": [
        "JavaScript",
        "TypeScript",
        "CSS",
        "SCSS",
        "Less", 
        "JSX",
        "Vue",
        "GraphQL",
        "JSON",
        "Markdown"
    ],
    "configs": [
        ".prettierrc",
        "prettier.config.js"
    ],
    "license": "MIT"
}

=== repometric/linterhub/engine/sitevalidator/meta.json
{
    "$schema": "https://repometric.github.io/linterhub/schema/meta.json",
    "name": "sitevalidator",
    "description": "site_validator is the free, open source version of the Site Validator app.",
    "url": "https://github.com/sitevalidator/site_validator",
    "languages": [
        "Ruby"
    ],
    "license": "MIT"
}

=== repometric/linterhub/engine/prospector/meta.json
{
    "$schema": "https://repometric.github.io/linterhub/schema/meta.json",
    "name": "prospector",
    "description": "Prospector is a tool to analyse Python code and output information about errors, potential problems, convention violations and complexity.",
    "url": "https://github.com/PyCQA/prospector",
    "languages": [
        "Python"
    ],
    "configs": [
        ".prospector"
    ],
    "license": "GPL-2.0"
}

=== repometric/linterhub/engine/jshint/meta.json
{
    "$schema": "https://repometric.github.io/linterhub/schema/meta.json",
    "name": "jshint",
    "description": "JSHint is a community-driven tool that detects errors and potential problems in JavaScript code",
    "url": "http://jshint.com",
    "languages": [
        "JavaScript"
    ],
    "license": "MIT"
}

=== repometric/linterhub/engine/ocstyle/meta.json
{
    "$schema": "https://repometric.github.io/linterhub/schema/meta.json",
    "name": "ocstyle",
    "description": "OCStyle is a Objective-C style checker",
    "url": "https://github.com/Cue/ocstyle",
    "languages": [
        "Python",
        "Objective-C"
    ],
    "license": "Apache-2.0"
}

=== repometric/linterhub/engine/stylint/meta.json
{
    "$schema": "https://repometric.github.io/linterhub/schema/meta.json",
    "name": "stylint",
    "description": "A linter for stylus",
    "url": "https://github.com/SimenB/stylint#readme",
    "languages": [
        "CSS"
    ],
    "configs": [
        ".stylintrc"
    ],
    "license": "AGPL-3.0"
}

=== repometric/linterhub/engine/html-inspector/meta.json
{
    "$schema": "https://repometric.github.io/linterhub/schema/meta.json",
    "name": "html-inspector",
    "description": "HTML Inspector is a code quality tool to help you and your team write better markup. It's written in JavaScript and runs in the browser, so testing your HTML has never been easier.",
    "url": "https://github.com/philipwalton/html-inspector",
    "languages": [
        "HTML"
    ],
    "license": "MIT"
}

=== repometric/linterhub/engine/pycodestyle/meta.json
{
    "$schema": "https://repometric.github.io/linterhub/schema/meta.json",
    "name": "pycodestyle",
    "alias": [
        "pep8"
    ],
    "description": "Pycodestyle is a tool to check your Python code against some of the style conventions in PEP 8.",
    "url": "https://github.com/PyCQA/pycodestyle",
    "languages": [
        "Python"
    ],
    "license": "MIT"
}
