=== repometric/linterhub/hub/.schema/engine.json
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "title": "This schema describes the engine definition",
    "description": "The meta information of engine",
    "type": "object",
    "properties": {
        "$schema": {},
        "id": {
            "type": "string",
            "description": "The engine id, used only when the engine name is not unique",
            "default": ""
        },
        "name": {
            "type": "string",
            "description": "The engine official name, may not be unique"
        },
        "description": {
            "type": "string",
            "description": "The engine official description"
        },
        "url": {
            "type": "string",
            "description": "The engine url (homepage, documentation or repository)",
            "format": "uri"
        },
        "areas": {
            "type": "array",
            "description": "The engine areas",
            "items": {
                "$ref": "#/definitions/area"
            }
        },
        "languages": {
            "type": "array",
            "description": "The list of supported languages",
            "items": {
                "$ref": "#/definitions/language"
            }
        },
        "extensions": {
            "type": "array",
            "description": "Common file extensions parsed by engine, if empty then corresponding language extensions are used",
            "items": {
                "type": "string"
            }
        },
        "configs": {
            "type": "array",
            "description": "List of file names which could be treated as engine config",
            "items": {
                "type": "string"
            }
        },
        "license": {
            "type": "string",
            "description": "The engine license",
            "$ref": "#/definitions/license"
        },
        "agreement": {
            "type": "string",
            "description": "The engine custom agreement"
        }
    },
    "required": [
        "name",
        "description",
        "url",
        "languages",
        "license"
    ],
    "additionalProperties": true,
    "definitions": {
        "area": {
            "type": "string",
            "description": "The engine area",
            "enum": [
                "code simplification",
                "commented code",
                "complexity",
                "documentation",
                "duplication",
                "formatting",
                "grammar",
                "memory leak",
                "security",
                "simplification",
                "smell",
                "spelling",
                "syntax",
                "unreachable code",
                "unused code"
            ]
        },
        "license": {
            "type": "string",
            "description": "The engine license",
            "enum": [
                "Custom",
                "Unknown",
                "AGPL-3.0",
                "Apache-2.0",
                "BSD-3-Clause",
                "MIT",
                "ISC"
            ]
        },
        "language": {
            "type": "string",
            "description": "The engine language or format",
            "enum": [
                "text",
                "coffeescript",
                "css",
                "html",
                "xml",
                "javascript",
                "json",
                "jsx",
                "sass",
                "typescript",
                "c",
                "cpp",
                "csharp",
                "groovy",
                "php",
                "ruby",
                "fortran",
                "plsql",
                "scala",
                "objectivec",
                "perl",
                "swift",
                "python",
                "java",
                "pug"
            ]
        }
    }
}

=== repometric/linterhub/hub/html-inspector/engine.json
{
    "$schema": "./../.schema/engine.json",
    "name": "html-inspector",
    "description": "HTML Inspector is a code quality tool to help you and your team write better markup. It's written in JavaScript and runs in the browser, so testing your HTML has never been easier.",
    "url": "https://github.com/philipwalton/html-inspector",
    "areas": [],
    "languages": [
        "html"
    ],
    "configs": [
        ".js"
    ],
    "license": "MIT"
}
